spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://172.17.0.3/myshop?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://172.17.0.4/myshop?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  aop: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.zfl.myshop.pojo.mapper: trace

wechat:
  mpAppId: wxdb23f1a1834b28ff
  mpAppSecret: 1a13ef5930b0b605321a31d28b7192ae
  openAppId: wx6ad144e54af67d87
  AppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /root/h5p/h5.p12
  notifyUrl: http://zhangfanglong.cn/sell/pay/notify

projectUrl:
  wechatMpAuthorize: http://zhangfanglong.cn
  wechatOpenAuthorize: http://sell.springboot.cn
  sell: http://zhangfanglong.cn
server:
  servlet:
    context-path: /sell
